In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('customers_data.csv')

In [5]:
df

,Company_ID,Company_Name,Company_Profit,Address
0,1.0,Tech Enterprises 1,80701.0,"EDSA, Barangay 606, Pasig, Philippines"
1,2.0,Global Partners 2,80511.0,"Commonwealth Ave, Barangay 789, Taguig, Philip..."
2,3.0,Quantum Associates 3,110664.0,"Roxas Blvd, Barangay 505, Pasig, Philippines"
3,4.0,Prime Network 4,NaN,"Alabang-Zapote Rd, Barangay 202, Taguig, Phili..."
4,5.0,Elite Ventures 5,69427.0,"Ayala Avenue, Barangay 101, Makati, Philippines"
...,...,...,...,...
95,96.0,Dynamic Network 96,101428.0,"Alabang-Zapote Rd, Brgy. 456, Cebu City, Phili..."
96,97.0,Quantum Holdings 97,33449.0,"EDSA, Barangay 789, Manila, Philippines"
97,98.0,Pioneer Ventures 98,71095.0,"Roxas Blvd, Barangay 123, Taguig, Philippines"
98,NaN,Elite Corp 99,107929.0,"Alabang-Zapote Rd, Barangay 303, Makati, Phili..."
99,100.0,Global Solutions 100,NaN,"Ayala avenue, barangay 456, taguig, philippines"

In [7]:
df.head()

,Company_ID,Company_Name,Company_Profit,Address
0,1.0,Tech Enterprises 1,80701.0,"EDSA, Barangay 606, Pasig, Philippines"
1,2.0,Global Partners 2,80511.0,"Commonwealth Ave, Barangay 789, Taguig, Philip..."
2,3.0,Quantum Associates 3,110664.0,"Roxas Blvd, Barangay 505, Pasig, Philippines"
3,4.0,Prime Network 4,NaN,"Alabang-Zapote Rd, Barangay 202, Taguig, Phili..."
4,5.0,Elite Ventures 5,69427.0,"Ayala Avenue, Barangay 101, Makati, Philippines"

In [22]:
df.set_index('Company_Profit', inplace=True)

In [24]:
df

,Company_Name,Address
Company_Profit,,
80701.0,Tech Enterprises 1,"EDSA, Barangay 606, Pasig, Philippines"
80511.0,Global Partners 2,"Commonwealth Ave, Barangay 789, Taguig, Philip..."
110664.0,Quantum Associates 3,"Roxas Blvd, Barangay 505, Pasig, Philippines"
NaN,Prime Network 4,"Alabang-Zapote Rd, Barangay 202, Taguig, Phili..."
69427.0,Elite Ventures 5,"Ayala Avenue, Barangay 101, Makati, Philippines"
...,...,...
101428.0,Dynamic Network 96,"Alabang-Zapote Rd, Brgy. 456, Cebu City, Phili..."
33449.0,Quantum Holdings 97,"EDSA, Barangay 789, Manila, Philippines"
71095.0,Pioneer Ventures 98,"Roxas Blvd, Barangay 123, Taguig, Philippines"
107929.0,Elite Corp 99,"Alabang-Zapote Rd, Barangay 303, Makati, Phili..."
NaN,Global Solutions 100,"Ayala avenue, barangay 456, taguig, philippines"

In [28]:
df.isnull().sum()

Company_Name    0
Address         0
dtype: int64